name: DeveloperTools
version: ${project.version}
main: com.bubladecoding.developertools.DeveloperTools
authors: [bublade]
description: Tools for developer while developing plugins
api-version: '1.13'
commands:
  test:
    description: Test Command.
  gimme:
    description: Gimme command for getting items.
