name: DeveloperTools
version: ${project.version}
main: com.bubladecoding.developertools.DeveloperTools
authors: [bublade]
softdepend: [McPluginBase]
description: Tools for developer while developing plugins
api-version: '1.13'
commands:
  test:
    description: Test Command.
  fly:
    description: Test Command.
  gimme:
    description: Gimme command for getting items.
    usage: gimme <material> [amount] [player]
  permissions:
    description: permission gommand
    usage: permissions --help or -h for more info
